name: UpdatePak
on:
  schedule:
    - cron: '20 23 * * *'
  workflow_dispatch:

jobs:
  updatepak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
    
      - name: Run u4pak
        run: |
            python src/u4pak.py pack -z Release/HMS_00-WindowsNoEditor_P.pak HMS_00
    
      - name: Create Release Directory
        run: |
          TimeZone="Asia/Bangkok"
          Tag=$(TZ=$TimeZone date +'%d%m%Y')
          echo "MY_TAG=$Tag" | tee -a $GITHUB_ENV
          Path="Release/HMS_00/Content/Paks"
          mkdir -p $Path
          cp Release/HMS_00-WindowsNoEditor_P.pak $Path

      - name: Create 7z Archive
        run: |
          ls -l Release 
          cd Release
          7z a -t7z "./HMS_TH_${{ env.MY_TAG }}.7z" "HMS_00/" -mx=9 -ms
          cd ../

      - name: Create Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: Release/*.7z
          release_name: ${{ env.MY_TAG }}
          tag: ${{ env.MY_TAG }}
          overwrite: true
